# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 672d51342279456d8376c709a994de85700f5a529c42a4c7d711c08fa1071789927d5c4e7b331e428923ce42f0c61fee0d05e918bd3fc54cc18ae74c532fabb0

test:
  secret_key_base: ada8737ac8cb66c800af532ac6e7533ea245cdb3b2ea5ff9563b4966d0374e863e7924da7e4dfd6274a2012592f456f0c34ffdb66c6862bfbadf24607a4e394e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
