# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c82cf987b276af55fda5d4a46e484e554f572e04090cf5c56018d4c2416a1a404117522ce2ae67496477cb7681085691c61ce1494b01aead4f5cfcab42160738

test:
  secret_key_base: a91b868be84f92eaea697bf34872ae8abe29757529a5f189d33519fea51513fa13f98c5db0c6838aa799977ece678452827856e49f98bae166547db60e003ba0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
